version: '3.9'

services:
  mysql:
    #maybe path not correct
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    # image: mariadb
    # check for file permission after setup
    volumes:
      - db_volume:/var/lib/mysql
    #   - /Users/kklockow/home/kklockow/data/wp_volume:/var/lib/mysql
    env_file: "environment.env"
    # environment:
    #   MYSQL_ROOT_PASSWORD: mysql_root_pass
    #   MYSQL_DATABASE: db_name
    #   MYSQL_USER: user_name
    #   MYSQL_PASSWORD: user_pass
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - db_network
    # wordpress placeholder

  wordpress:
    # image: wordpress:php7.3-fpm-alpine
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp_volume:/var/www/html
    #   - /Users/kklockow/home/kklockow/data/wp_volume:/var/www/html
    depends_on:
      - mysql
    env_file: "environment.env"
    # environment:
    #   WORDPRESS_DB_HOST: mysql
    #   MYSQL_ROOT_PASSWORD: mysql_root_pass
    #   WORDPRESS_DB_NAME: db_name
    #   WORDPRESS_DB_USER: user_name
    #   WORDPRESS_DB_PASSWORD: user_pass
    #   WORDPRESS_TABLE_PREFIX: wp_
    # ports:
      # - "3306:3306"
    # links:
    #   - mysql
    networks:
      - wp_network
      - db_network
    # restart: always

  nginx:
    # image: nginx:alpine
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wp_volume:/var/www/html
    #   - /Users/kklockow/home/kklockow/data/wp_volume:/var/www/html
    # volumes:
    #   - nginx:/etc/nginx/conf.d
    #   - /data/html:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    # links:
    #   - wordpress
    networks:
      - wp_network
    restart: always

volumes:
  db_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/kklockow/home/kklockow/data/db_volume
  wp_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/kklockow/home/kklockow/data/wp_volume

networks:
  wp_network:
  db_network: