version: '3'
services:
  mysql:
    #maybe path not correct
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    # image: mariadb
    # check for file permission after setup
    volumes:
      - /Users/kklockow/home/kklockow/data:/var/lib/mysql
    env_file: "environment.env"
    # environment:
    #   MYSQL_ROOT_PASSWORD: mysql_root_pass
    #   MYSQL_DATABASE: db_name
    #   MYSQL_USER: user_name
    #   MYSQL_PASSWORD: user_pass
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - db_network
    # wordpress placeholder

  wordpress:
    # image: wordpress:php7.3-fpm-alpine
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - /Users/kklockow/home/kklockow/data:/var/www/html
    depends_on:
      - mysql
    env_file: "environment.env"
    # environment:
    #   WORDPRESS_DB_HOST: mysql
    #   MYSQL_ROOT_PASSWORD: mysql_root_pass
    #   WORDPRESS_DB_NAME: db_name
    #   WORDPRESS_DB_USER: user_name
    #   WORDPRESS_DB_PASSWORD: user_pass
    #   WORDPRESS_TABLE_PREFIX: wp_
    ports:
      - "3306:3306"
    # links:
    #   - mysql
    networks:
      - wp_network
      - db_network
    restart: always

  nginx:
    # image: nginx:alpine
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - /Users/kklockow/home/kklockow/data:/var/www/html
    # volumes:
    #   - nginx:/etc/nginx/conf.d
    #   - /data/html:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    # links:
    #   - wordpress
    networks:
      - wp_network
    restart: always

networks:
  wp_network:
  db_network: