# version: '3.9'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db_volume:/var/lib/mysql
    env_file: "environment.env"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - inception_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp_volume:/var/www/html
    depends_on:
      - mariadb
    env_file: "environment.env"
    networks:
      - inception_network
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wp_volume:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: always

volumes:
  db_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/kklockow/data/db_volume
  wp_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/kklockow/data/wp_volume

networks:
  inception_network: