version: '3'
services:
  mysql:
    #maybe path not correct
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    # image: mariadb
    # check for file permission after setup
    volumes:
      - /home/login/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass
    restart: always

    # wordpress placeholder

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - /home/login/data:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    restart: always

  nginx:
    # image: nginx:alpine
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - /home/login/data:/var/www/html
    # volumes:
    #   - nginx:/etc/nginx/conf.d
    #   - /data/html:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress